apiVersion: 1

contactPoints:
  - orgId: 1
    name: n8n-webhook
    receivers:
      - uid: n8n-webhook-receiver
        type: webhook
        settings:
          url: http://host.docker.internal:35678/webhook/pui-alert-router/grafana-webhook/grafana-alert
          httpMethod: POST
          maxAlerts: 0
          title: "{{ .CommonLabels.alertname }}"
          message: "{{ template \"default.message\" . }}"
